=== ccjmne/ccjmne-resume/src/profile.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://github.com/ccjmne/ccjmne-resume/profile.schema.json",
  "type": "object",
  "required": ["links", "identity", "experience"],
  "properties": {
    "links": {
      "$id": "#/properties/links",
      "type": "array",
      "items": {
        "$id": "#/properties/links/items",
        "type": "object",
        "required": ["icon", "href", "text"],
        "properties": {
          "icon": {
            "$id": "#/properties/links/items/properties/icon",
            "type": "string"
          },
          "href": {
            "$id": "#/properties/links/items/properties/href",
            "type": "string"
          },
          "text": {
            "$id": "#/properties/links/items/properties/text",
            "type": "string"
          }
        }
      }
    },
    "identity": {
      "$id": "#/properties/identity",
      "type": "object",
      "required": ["name", "title", "summary"],
      "properties": {
        "name": {
          "$id": "#/properties/identity/properties/name",
          "type": "string"
        },
        "title": {
          "$id": "#/properties/identity/properties/title",
          "type": "string"
        },
        "summary": {
          "$id": "#/properties/identity/properties/summary",
          "type": "string"
        }
      }
    },
    "education": {
      "$id": "#/properties/education",
      "type": "array",
      "items": {
        "$id": "#/properties/education/items",
        "type": "object",
        "required": ["degree", "field"],
        "properties": {
          "degree": {
            "$id": "#/properties/education/items/properties/degree",
            "type": "string"
          },
          "field": {
            "$id": "#/properties/education/items/properties/field",
            "type": "string"
          },
          "dates": {
            "$id": "#/properties/education/items/properties/dates",
            "type": "string"
          },
          "highlight": {
            "$id": "#/properties/education/items/properties/highlight",
            "type": "string"
          }
        }
      }
    },
    "endorsments": {
      "$id": "#/properties/endorsments",
      "type": "array",
      "items": {
        "$id": "#/properties/endorsments/items",
        "type": "object",
        "required": ["from", "title", "excerpt"],
        "properties": {
          "from": {
            "$id": "#/properties/endorsments/items/properties/from",
            "type": "string"
          },
          "title": {
            "$id": "#/properties/endorsments/items/properties/title",
            "type": "string"
          },
          "excerpt": {
            "$id": "#/properties/endorsments/items/properties/excerpt",
            "type": "string"
          }
        }
      }
    },
    "skills": {
      "$id": "#/properties/skills",
      "type": "array",
      "items": {
        "$id": "#/properties/skills/items",
        "type": "string"
      }
    },
    "experience": {
      "$id": "#/properties/experience",
      "type": "array",
      "items": {
        "$id": "#/properties/experience/items",
        "type": "object",
        "required": ["dates", "duration", "company", "location", "title", "abstract"],
        "properties": {
          "dates": {
            "$id": "#/properties/experience/items/properties/dates",
            "type": "string"
          },
          "duration": {
            "$id": "#/properties/experience/items/properties/duration",
            "type": "string"
          },
          "company": {
            "$id": "#/properties/experience/items/properties/company",
            "type": "string"
          },
          "location": {
            "$id": "#/properties/experience/items/properties/location",
            "type": "string"
          },
          "title": {
            "$id": "#/properties/experience/items/properties/title",
            "type": "string"
          },
          "abstract": {
            "$id": "#/properties/experience/items/properties/abstract",
            "type": "string"
          },
          "tags": {
            "$id": "#/properties/experience/items/properties/tags",
            "type": "array",
            "items": {
              "$id": "#/properties/experience/items/properties/tags/items",
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== ccjmne/ccjmne-resume/src/profile.json
{
  "links": [{
    "icon": "mail.svg",
    "href": "mailto:y.moroitsu@valencia.com",
    "text": "y.moroitsu@valencia.com"
  }, {
    "icon": "house.svg",
    "href": "https://www.google.com/maps/place/Valencia,+Spain",
    "text": "1–2 Main St., Arehaza City"
  }, {
    "icon": "linkedin.svg",
    "href": "https://www.linkedin.com/in/moroitsu.yaalon",
    "text": "linkedin/moroitsu.yaalon"
  }, {
    "icon": "facebook.svg",
    "href": "https://facebook.com/y.moroitsu",
    "text": "facebook/y.moroitsu"
  }],
  "identity": {
    "name": "Yaalon MOROITSU",
    "title": "Gentle like Moonlight",
    "summary": "On my free time, I grind Turos and perform fire acrobatics in the forest.\nThey actually named that ghoulish zone \"Ash Forest\" after a particularly eventful representation of mine that will never be forgotten.\nI can hold deadlines, too."
  },
  "skills": ["Growing Dalvenia Alreas", "Grinding Turos", "Failing PENs", "Recruiting idjits", "One versus One", "One versus Two", "One versus Three", "Being of service"],
  "experience": [{
    "dates": "Sep. 285 – Present",
    "duration": "7 months",
    "company": "ExplorersGuild",
    "location": "from Kamasylvia to Valencia",
    "title": "Recruiter & Party Planner",
    "abstract": "Keeping the communication channels busy and entertaining at all times.\nPart of the hiring team that discovered the rarest of pearls ever recruited."
  }, {
    "dates": "Jul. 283 – Sep. 285",
    "duration": "2 years 3 months",
    "company": "Moronitsu Ltd.",
    "location": "Round Sulfur Mines, Valencia area",
    "title": "Intelligence Officer",
    "abstract": "In a secret mission to the Middle-East. Grinded undercover for a while, reporting directly to ██████ ████████.\nSingle-handedly overturned plots from the ███████████ government.\nBrought the ████████████ ██ ██████ conspiracy to light."
  }, {
    "dates": "Apr. 282 – Jul. 283",
    "duration": "1 year 4 months",
    "company": "Shakatu Furnitures & Co.",
    "location": "Arehaza City",
    "title": "Interior Designer",
    "abstract": "Designed and promoted our most prominent display home to date.\nProject highlighted by the Calpheon Metropolis Magazine as a prime example of contemporary interior design trends."
  }, {
    "dates": "Nov. 281 – Apr. 282",
    "duration": "6 months",
    "company": "ThatHappened Inc.",
    "location": "All over the place",
    "title": "Ninja (Contractor job)",
    "abstract": "Tried my hands at a less-irrelevant class.\nTurns out Musa is just right for me."
  }, {
    "dates": "Jun. 279 – Nov. 281",
    "duration": "2 years 6 months",
    "company": "Teff International",
    "location": "Red Desert, Valencia area",
    "title": "Industrial Magnate",
    "abstract": "Establised a sprawling worker empire that directly impacts the global Marketplace.\nSet up precise protocols so that this corporation practically runs itself."
  }, {
    "dates": "May. 278 – Jun. 279",
    "duration": "1 year 2 months",
    "company": "Stonetail Ranch",
    "location": "Central Mediah",
    "title": "Horse Breeder",
    "abstract": "Lovingly cared for our most magnificient animals.\nProud father of a mythical Diné and his little Arduanatt sister."
  }, {
    "dates": "Oct. 275 – May. 277",
    "duration": "1 year 8 months",
    "company": "The Behr Bear Brothers",
    "location": "Margoria and Serendia",
    "title": "Competitive Hunter",
    "abstract": "Reached First Place at the 277 Olympic Games in both Whale and Khalk categories."
  }],
  "education": [{
    "degree": "Doctorate's Degree",
    "field": "Valencian Ecology",
    "highlight": "Learned to appreciate the most delicate flora of our world.\nGraduated top of my class."
  }, {
    "degree": "Master's Degree",
    "field": "Balenos Cuisine",
    "dates": "2008 – 2010",
    "highlight": "Focused primarily on refining recipes to elevate Pickled Vegetables to the status of delicacy."
  }, {
    "degree": "Apprenticeship",
    "field": "Occult Arts",
    "dates": "2005 – 2008",
    "highlight": "Trained in Weapon Enchanting by the Black Spirit, the most famous university lecturer in all Blackstone matters.\nDegree obtained after a decade of practice."
  }],
  "endorsments": [{
    "from": "Karine NINOSHKA",
    "title": "Duvencrunian Statue",
    "excerpt": "[...] a very talented individual, tackling all assignments with dedication.\nI highly recommend Yaalon, he is a team player and would make a great asset to any organisation."
  }, {
    "from": "Anonymous PKer",
    "title": "Master Duellist",
    "excerpt": "Yaalon showed obvious technical skills and remarkable maternal abilities.\nDon't try to poke the bear, 'cause his Crescent Blade pokes back pretty hard."
  }]
}
